### ISSUE TITLE
找不到符号 符号:   类 AsyncTaskCompat

### ISSUE THREAD

**Issue by jiayuliang1314** [weizongwei5/AndroidScreenShot_SysApi#10]
Error:(19, 29) 错误: 找不到符号
符号:   类 AsyncTaskCompat
位置: 程序包 android.support.v4.os
Error:(98, 41) 错误: 找不到符号
符号: 变量 AsyncTaskCompat

**Comment by HuRuWo** [comment]
这个方法在高版本的sdk中移除了 要不降低sdk版本 要不使用替代方法

**Comment by BruceWind** [comment]
最新提交已经修复。

**Comment by BruceWind** [comment]
即将关闭这个issues.
