### ISSUE TITLE
录屏代码太复杂了 录屏结果 可以变成流媒体实时传给服务器 这个怎么写呢 求大佬看看 谢谢谢谢🙏🙏🙏🙏🙏

### ISSUE THREAD

**Issue by tghjnjvg** [weizongwei5/AndroidScreenShot_SysApi#13]
录屏代码太复杂了 录屏结果 可以变成流媒体实时传给服务器 这个怎么写呢
求大佬看看 谢谢谢谢🙏🙏🙏🙏🙏

**Comment by BruceWind** [comment]
firstly, i would say thanks for your issue.
and, reatime stream is really difficult for me. that need to add encode stream,push with rtmp or rtsp protocol. it is really really complex.

**Comment by BruceWind** [comment]
but, i can give you some suggestions, 
pls look at https://github.com/android/media-samples .
this repo has record and encode data from camera,then save to disk. but it desnt publish to server.
i think that you has to establish a stream-server with rtsp or rtmp protocol.
you can buy a Raspberry Pi which you establish a  stream-server on.

**Comment by BruceWind** [comment]
there is a better repo : https://github.com/eterrao/ScreenRecorder.
