### ISSUE TITLE
android 10以后版本这个API只能在前台服务内调用，故shotter类需要一些更改

### ISSUE THREAD

**Issue by wangziyannb** [weizongwei5/AndroidScreenShot_SysApi#14]
普通服务调用会出以下错误：
java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

通过权限activity创建Shotter实例后，SaveTask倒是满足了实例化必须在UI线程的要求，但是在前台服务中调用getScreenshot()，不属于UI线程。因为shotter类关键的SaveTask中doInBackground()能在后台进行，故截屏是能完成的。但由于onPostExecute()只能于UI线程中跑，导致onPostExecute()失效，所作的资源释放、callback工作都直接忽略了。

解决方法：把onPostExecute()内的工作直接续到doInBackground()中即可。

**Comment by BruceWind** [comment]
thanx alot for your issue。

**Comment by BruceWind** [comment]
could you  pls create a pull request give to me?

**Comment by wangziyannb** [comment]
@BruceWind 已提交

**Comment by BruceWind** [comment]
thanx.
