### ISSUE TITLE
直接编译build错误

### ISSUE THREAD

**Issue by cooture** [weizongwei5/AndroidScreenShot_SysApi#16]
```
/Users/***/AndroidStudioProjects/AndroidScreenShot_SysApi/app/src/main/java/com/androidyuan/androidscreenshot_sysapi/MainActivity.java:57: 错误: 不是封闭类: ScreenShotActivity
                    Shotter shotter = new Shotter(ScreenShotActivity.this, resultCode, data);
                                                                    ^
```
Android Stdio直接git下来的，直接build失败

**Comment by RealMoMo** [comment]
> ```
> /Users/***/AndroidStudioProjects/AndroidScreenShot_SysApi/app/src/main/java/com/androidyuan/androidscreenshot_sysapi/MainActivity.java:57: 错误: 不是封闭类: ScreenShotActivity
>                     Shotter shotter = new Shotter(ScreenShotActivity.this, resultCode, data);
>                                                                     ^
> ```
> 
> Android Stdio直接git下来的，直接build失败

应该是开发者，直接从lib copy过来没修改，改用MainActivity.this 即可

**Comment by BruceWind** [comment]
Okay, I got it. I will solve it todady.
It is my fault , I want to modify some code. and I wanted to push it to dev branch,but I pushed it to master. I'm sorry.
