### ISSUE TITLE
截屏图片生成后未通知图库更新

### ISSUE THREAD

**Issue by scauzhangpeng** [weizongwei5/AndroidScreenShot_SysApi#3]
截屏文件生成后，没有进行图库更新操作。
Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
Uri uri = Uri.fromFile(fileImage);
intent.setData(uri);
getContext().sendBroadcast(intent);

**Comment by BruceWind** [comment]
首先说声抱歉！

这个项目你可以理解为一个SDK，所以我没有需求通知刷新图库。
