### ISSUE TITLE
截屏后的截图罩着一层浅黑色颜色

### ISSUE THREAD

**Issue by guangzq** [weizongwei5/AndroidScreenShot_SysApi#4]
这样就不是原屏幕了

**Comment by BruceWind** [comment]
你好！针对这个问题，我先说声：抱歉！
然后，请提供机型，系统版本这些基础信息我去跟进一下？

**Comment by weizongwei5** [comment]
给你提供两个解决方案:
1.猜测可能是因为你被截屏的activity 走了onPause导致的或者你的一些控件在activity onPause的时候会变暗,通过修改给我manifest中配置的截图activity的主题来解决,目前是透明主题,你改为Dialog主题试试.
2.猜测你这个设备不能用我代码里写死的颜色,你可以试试修改代码里的色彩配置.

**Comment by weizongwei5** [comment]
长时间不回复 我会关闭这个issue.

**Comment by McoWu** [comment]
我红米4X为什么点开始，然后没有任何反应呢？还需要人为的去操作什么吗？

**Comment by BruceWind** [comment]
首先抱歉，我这里没有4X这个机型，无法对您的问题进行复现。
然后你看代码里：截图成功后会执行：
```
toast("shot finish!");
```

**Comment by McoWu** [comment]
你好，感谢回复。我现在打开那个应用就是显示一个Hello world。然后没有任何的反应，也没有您说的那个toast，我想问一下，他是自己触发截屏呢还是需要我们人为的去操作什么




------------------ 原始邮件 ------------------
发件人: "weizongwei5";<notifications@github.com>;
发送时间: 2017年12月21日(星期四) 上午10:44
收件人: "weizongwei5/AndroidScreenShot_SysApi"<AndroidScreenShot_SysApi@noreply.github.com>;
抄送: "那年我十八ii"<1044756111@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [weizongwei5/AndroidScreenShot_SysApi] 截屏后的截图罩着一层浅黑色颜色 (#4)




首先抱歉，我这里没有4X这个机型，无法对您的问题进行复现。
 然后你看代码里：截图成功后会执行：
 toast("shot finish!");

**Comment by BruceWind** [comment]
hello world 下面有个start按钮 ，需要点击一下，后面代码都会执行。 
你要做的就是点一下 hello world 下面的start按钮

**Comment by BruceWind** [comment]
怀疑你是执行了cancel,之后就不再弹窗申请权限了，你断点调试看下走到了哪里停下了。

------------------------------------------


2018/04.24: 刚刚我把代码里的被用户取消的逻辑加了toast。

**Comment by wang521314** [comment]
你好，我现在报了java.lang.UnsupportedOperationException: The producer output buffer format 0x5 doesn't match the ImageReader's configured buffer format 0x1.这个异常，根据解释说是我觉得是PixelFormat.RGBA_8888与Bitmap.Config.ARGB_8888不符的原因，请问这怎么解决，手机魅族mx3

**Comment by BruceWind** [comment]
你试试修改 [Shotter.java 58行](https://github.com/weizongwei5/AndroidScreenShot_SysApi/blob/009ae1e952475b69bb8c34c4f2b39e6dfe656c70/libshot/src/main/java/com/androidyuan/lib/screenshot/Shotter.java#L58)

修改为别的，然后给我一个反馈。
@wang521314   我已经修改了颜色，之前的颜色可能对多种手机适配有一些问题。

**Comment by welthy** [comment]
您好，我报了：
java.lang.UnsupportedOperationException: The producer output buffer format 0x1 doesn't match the ImageReader's configured buffer format 0x4.
这个异常，请问怎么解决？
还有截屏为什么是黑的？

**Comment by welthy** [comment]
保存在外部存储是SD卡上的意思吗？ 我想保存在本地相册里怎么做呢？

**Comment by BruceWind** [comment]
java.lang.UnsupportedOperationException

我已经修改了颜色，之前的颜色可能对多种手机适配有一些问题。

**Comment by BruceWind** [comment]
保存在外部存储是SD卡上的意思吗？ 我想保存在本地相册里怎么做呢？ 

请看保存图片的代码，自行修改。

**Comment by welthy** [comment]
我改了ImageReader的颜色就好了。

**Comment by BruceWind** [comment]
请补充你改动了哪里，到这个issues上。

**Comment by welthy** [comment]
Bitmap bitmap = Bitmap.createBitmap(width + rowPadding / pixelStride, height,
                    Bitmap.Config.ARGB_8888);
这句代码的最后一个参数。

**Comment by JRuAndroid** [comment]
浅黑色颜色到底怎么去掉的？

**Comment by BruceWind** [comment]
什么机型？
Shotter.java   有几个RGB配置，你试着改下。看下好了没

**Comment by JRuAndroid** [comment]
我的是小米4s

**Comment by BruceWind** [comment]
抱歉，我没有这个机型。。。。

**Comment by JRuAndroid** [comment]
不能用565，截得图是一片黄色

**Comment by BruceWind** [comment]
@guangzq  我看了下这个一层灰色的问题，是第一次权限弹窗，之后立马执行截屏导致的，如果你权限弹窗之后，第二次启动截图就不会了。

**Comment by BruceWind** [comment]
@JRuAndroid   @guangzq   
找机器测试了下，你们的机器确实是小米，这个灰色 应该是这个弹窗的消失过程的阴影导致的。

**Comment by BruceWind** [comment]
@McoWu  hello world 文字已经修改。
