### ISSUE TITLE
反复截屏

### ISSUE THREAD

**Issue by YenRen** [weizongwei5/AndroidScreenShot_SysApi#5]
一秒钟截屏至少5次  而后一直有个截屏的线程      这样 一直会有一全透明的activity 浮在窗口上
  以至点击不到其它应用  （启动不了其它应用）  而且 还杀不掉进程。。。。。
这要怎么处理

**Comment by BruceWind** [comment]
1.反复截屏这个情况是你改了代码主动做的?
2.杀不掉?  不可能杀不掉啊 除非你开了多进程.


ps;我代码里没有做多次截屏也没有做多进程啊.
