### ISSUE TITLE
Nexus5 Android6.0.1 截屏有黑框

### ISSUE THREAD

**Issue by ohyeah521** [weizongwei5/AndroidScreenShot_SysApi#6]
Nexus5，Andorid6.0.1 官方系统，用了您的测试程序截屏有黑框，系统自带截屏没有，请问如何去掉黑框

**Comment by BruceWind** [comment]
能贴一个图吗？ 我看下

**Comment by BruceWind** [comment]
@ohyeah521   请看下是否同一个问题，我做了测试。

[issues4](https://github.com/weizongwei5/AndroidScreenShot_SysApi/issues/4)

**Comment by ohyeah521** [comment]
@weizongwei5  是这样的图片。目前测试遇到几个问题：
1、四周都有黑色的黑框
2、在有输入法输入状态的时候截取屏幕，会把输入状态取消掉
3、截取完毕后，状态栏的那个图标还一直在，就是使用MediaProjection产生的那个图标。如何删除图标？
![5af44c9594b9f](https://user-images.githubusercontent.com/1449374/39873253-fb930400-549c-11e8-9985-dc3128be1cee.jpg)

**Comment by BruceWind** [comment]
回复：
1.黑框问题你试试把日志打出来，看哪里取分辨率错了，还是createbitmap的时候弄错了。
2.这个我过几天看下。
3.这个无法解决，系统设计如此，使用投屏API 就会出现这个，如果任何一款app使用这个投屏服务却没有显示这个图标，就有可能用户信息泄漏。

**Comment by ohyeah521** [comment]
@weizongwei5 
1、黑框问题是正常了，是分辨率取的手机整个屏幕的分辨率
2、第二个问题比较棘手，每次截屏输入法状态就没了
3、第三个问题可以忽略了，嘿嘿
4、最后:感谢耐心解答^_^

**Comment by BruceWind** [comment]
@ohyeah521   
2.我截屏的时候 输入法可以用啊 .  你是使用ShotActivity  还是service?  键盘是什么键盘?

**Comment by ohyeah521** [comment]
@weizongwei5 我是用的service截屏的，后台截屏，键盘是谷歌输入法和搜狗拼音都不行

**Comment by BruceWind** [comment]
我看了下 无法截图输入法的原因:
我们截屏其实是service里启动一个透明的activity,这时候上个页面被pause,上个页面的输入法则会被系统隐藏.

**Comment by BruceWind** [comment]
你可以试着改成用activity方式截屏.把一些截屏的代码拷贝过来.

**Comment by BruceWind** [comment]
那个状态栏的图标我改了代码了,截图完成之后会自动隐藏.

**Comment by zhanglihow** [comment]
> @weizongwei5
> 1、黑框问题是正常了，是分辨率取的手机整个屏幕的分辨率
> 2、第二个问题比较棘手，每次截屏输入法状态就没了
> 3、第三个问题可以忽略了，嘿嘿
> 4、最后:感谢耐心解答^_^

我也遇到了黑框的问题，请问下，是修改了哪里的代码？

**Comment by zhanglihow** [comment]
> > @weizongwei5
> > 1、黑框问题是正常了，是分辨率取的手机整个屏幕的分辨率
> > 2、第二个问题比较棘手，每次截屏输入法状态就没了
> > 3、第三个问题可以忽略了，嘿嘿
> > 4、最后:感谢耐心解答^_^
> 
> 我也遇到了黑框的问题，请问下，是修改了哪里的代码？
我知道怎么改了

替换：  
```
   private int getScreenWidth() {
        return Resources.getSystem().getDisplayMetrics().widthPixels;
    }

    private int getScreenHeight() {
        return Resources.getSystem().getDisplayMetrics().heightPixels;
    }
```
为：
```
            WindowManager window = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
            Display mDisplay = window.getDefaultDisplay();
            DisplayMetrics metrics = new DisplayMetrics();
            mDisplay.getRealMetrics(metrics);
            int mWidth= metrics.widthPixels;//size.x;
            int mHeight= metrics.heightPixels;//size.y;
```

**Comment by BruceWind** [comment]
你可以给提个pull request把您的代码合入进来吗？感谢。

**Comment by zhanglihow** [comment]
> 你可以给提个pull request把您的代码合入进来吗？感谢。

好的

**Comment by BruceWind** [comment]
已经合入。
