### ISSUE TITLE
截桌面屏幕时,都会先跳转到MainActivity, 之后手动跳转到桌面,能否直接截桌面?

### ISSUE THREAD

**Issue by zhangcheng123** [weizongwei5/AndroidScreenShot_SysApi#8]
实际: MainActivity -> 点击按钮触发截屏 -> 手动转到桌面 ->  跳转MainActivity ->手动转到桌面 -> 截屏完成
期望: MainActivity -> 点击按钮触发截屏 ->手动转到桌面-> 截屏完成

**Comment by BruceWind** [comment]
使用service截屏。

**Comment by BruceWind** [comment]
代码是支持的,你实施service截屏,另外这个issues我要关闭了.
